[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_message_payment = "6yM6tgtjWJnoAGzrM7jP4oHwLXBfjkfJbszEFRtBTTaL"

[registry]
url = "https://api.apr.dev"

[provider]
# Where deployed
cluster = "Localnet"
# Where the keypair is stored for this
wallet = "/Users/colinrhys/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
